---
title: "Evolución en la pobreza de sectores rurales de chile"
author: "Mauricio Jara Saavedra"
format: html
editor: visual
bibliography: ejemplo0.1.bib
link-citations: true
---

Creado por: Mauricio Jara

# Variaciones en la evolución de la pobreza multidimensional en los sectores rurales de Chile.

La pobreza en Chile ha sido un fenómeno que ha acompañado al desarrollo del país constantemente y la medición de esta se ha realizado de manera más formal y sistemática a partir de la aplicación de la Encuesta de Caracterización Socioeconómica Nacional (CASEN), la cual ha implementado la medición de la pobreza multidimensional a partir del año 2013, con el fin de aportar a una comprensión más amplia y detallada de las condiciones de vida de la población.

ndefinedLa pobreza multidimensional en zonas rurales presenta particularidades significativas en comparación con las áreas urbanas, lo que manifiesta la necesidad de analizar detalladamente cómo factores como la educación,el trabajo, la vivienda, y las redes sociales impactan en la configuración de la pobreza en estos sectores.

. El propósito de
esta medida es complementar la medición de la pobreza basada en ingresos con un indicador que
refleje las condiciones de vida de la población en aspectos relevantes para el bienestar social y una
vida digna.

\*Comparar los sectores urbanos y rurales para ver como evoluciona la pobreza en el sector rural respecto al sector urbano.a partir de: el nivel educativo, el acceso a servicios básicos y la distribución del ingreso de la población chilena.

\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\--

## Primer ejemplo de citas:

la cita que se presenta a continuacion, fue rescatada como ejemplo de la practica de zotero junto a Research Rabbit:

[@larsosbergFairInequalityAttitudes2006]
